{% set name = "mysql" %}
{% set major_minor_version = "8.0" %}
{% set micro_version = "20" %}
{% set sha256 = "b6ad1a09eb146fa913f1afc257bbed8ffab688e2d504fb8ddb652f69f551a9c1" %}

package:
  name: {{ name|lower }}
  version: {{ major_minor_version }}.{{ micro_version }}

source:
  fn: mysql-boost-{{ major_minor_version }}.{{ micro_version }}.tar.gz
  url:  https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-boost-{{ major_minor_version }}.{{ micro_version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  merge_build_host: True

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - perl
    - make  # [unix]
    - pkg-config  # [not win]

test:
  commands:
    - mysql_config --version
    - my_print_defaults --version
    - mysqld --help --verbose
    - command -v mysql.server

about:
  home: https://www.mysql.com/
  license: GPL-2.0
  license_family: GPL
  license_file: COPYING
  summary: 'Open source relational database management system.'

  description: |
    The MySQL(TM) software delivers a very fast, multi-threaded, multi-user,
    and robust SQL (Structured Query Language) database server. MySQL Server
    is intended for mission-critical, heavy-load production systems as well
    as for embedding into mass-deployed software.

extra:
  recipe-maintainers:
    - beckermr
